version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Deque
  - humantime
  - instrs
  - miri
  - reborrow
  - Sched
  - scrutinee
  - thiserror
ignoreWords: []
import: []
